image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install -D typescript
    - npm install
    - mkdir -p output/static

testing_testing:
  stage: test
  script:
    - npm install -D typescript
    - npm install
    - npm test --coverage
    - mkdir -p output/static
