image: node:latest

stages:
  - build
  - test
  - integrationtest

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - yarn install
    - mkdir -p output/static

testing_testing:
  stage: test
  script:
    - yarn test
    - mkdir -p output/static

integration_testing:
    stage: integrationtest
    before_script:
        - apt-get -y install wget
        - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        - apt install -y ./google-chrome-stable_current_amd64.deb
    script:
        - yarn integrationtest
