image: satantime/puppeteer-node:current

stages:
  - build
  - test
  - integrationtest

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - yarn install
    - mkdir -p output/static

testing_testing:
  stage: test
  script:
    - yarn test
    - mkdir -p output/static

integration_testing:
    stage: integrationtest
    script:
        - yarn integrationtest
